{% set name = "torch_geometric" %}
{% set version = "1.6.0" %}

package:
  name: py{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fbf43fe15421c9affc4fb361ba4db55cb9d3c64d0c29576bb58d332bf6d27fef

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - pytest-runner
    - python
    - setuptools
  run:
    - python
    - googledrivedownloader
    - h5py
    - networkx
    - numba
    - numpy
    - tqdm
    - pandas
    - plyfile
    - rdflib
    - requests
    - scikit-learn
    - scipy
    - ase
    - pytorch
    - pytorch_cluster
    - pytorch_scatter
    - pytorch_sparse ==0.6.3
    - pytorch_spline_conv

test:
  imports:
    - torch_geometric

about:
  home: https://github.com/rusty1s/pytorch_geometric
  summary: Geometric Deep Learning Extension Library for PyTorch
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/rusty1s/pytorch_geometric

extra:
  recipe-maintainers:
    - rluria14
    - oblute
    - ndmaxar
