{% set name = "torch_geometric" %}
{% set version = "1.7.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/torch_geometric-{{ version }}.tar.gz
  sha256: a57b115cb3891c81d16960380e0bc4d842da2c96bea5ca019d6d139e6f026b31

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - pytest-runner
    - setuptools


  run:
    - googledrivedownloader
    - jinja2
    - networkx
    - numpy
    - pandas
    - pyparsing
    - python >=3.6
    - python-louvain
    - rdflib
    - requests
    - scikit-learn
    - scipy
    - tqdm
    - pytorch


test:
  imports:
    - torch_geometric
    - torch_geometric.data
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rusty1s/pytorch_geometric
  summary: Geometric Deep Learning Extension Library for PyTorch
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JohnKyzer
